### ISSUE TITLE
Parameter Change for 256 px Images

### ISSUE THREAD

**Issue by LucasK26** [milmor/TransGAN#3]
Hello, 

Thank you for your implementation!!
I would like to use it to generate 256 px images, or even larger 512px images. 

I was trying to adapt your code but everytime I think I have it another dimension error comes up. As you wrote the code your could maybe help me and tell me what I could change how to generate larger images with your implemenation. 

Cheers 
--Lucas

**Comment by milmor** [comment]
Hi,

The generator would require more "pixel_upsample(x, H, W)" stages till it reaches the 256. The discriminator would require just to increase the patch size. Although, with these modifications, the model becomes quite expensive to train. You can use FastGAN instead: https://github.com/milmor/self-supervised-gan it already works with 256 x 256.
